version: '3'
services: 

  # Configure a database service in a container
  database:
    image: sameersbn/postgresql:latest
    container_name: kamiony-db
    environment:
    - DB_NAME=kamiony-local,kamiony-test
    - PG_TRUST_LOCALNET=true
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
      
  # Configure a redis server in a container
  redis:
    image: redis:latest
    container_name: kamiony-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
    - 6379:6379